### ISSUE TITLE
Numpy array version / riemann

### ISSUE THREAD

**Issue by sunshineinsandiego** [DiGyt/asrpy#1]
Hi - Thanks for making this available! I'm wondering if you have a version of this that works on numpy arrays rather than mne epochs?  Also, do you have any recommendations for riemann asr implementations in python?

Thanks very much!

Note: I saw your comments here: https://github.com/mne-tools/mne-python/issues/7479 and your comparison of artifact removal methods here: https://digyt.github.io/automated_EEG_cleaning_comparison/. As I'm interested in on-line methods of artifact removal, have you run a comparison of your riemann vs. euclidean implementations?

**Comment by DiGyt** [comment]
Hey @sunshineinsandiego 

Thanks for your interest in asrpy :)

If you want to calculate ASR you can use the functions [asr_calibrate](https://github.com/DiGyt/asrpy/blob/3511c341aee8b92f50f87449572c7dc5ebe1c182/asrpy/asr.py#L326) and [asr_process](https://github.com/DiGyt/asrpy/blob/3511c341aee8b92f50f87449572c7dc5ebe1c182/asrpy/asr.py#L455). It should work more or less like this:
```python
from asrpy import asr_calibrate, asr_process

eeg_data = np.array()  # your eeg data as a 2D numpy array of shape (n_channels, n_samples)
sfreq = 128  # the sampling frequency of your data in Hz (e.g. 128 Hz)
cutoff = 20  # set a reasonable cutoff threshold (the old eeglab default of 5 is way too low)

M, T = asr_calibrate(eeg_data, sfreq, cutoff=cutoff)
clean_data = asr_process(eeg_data, sfreq, M, T)
```
These functions should be almost entirely equivalent to the original implementation in EEGLab's Clean_rawdata. Actually, the `ASR()` class with the `ASR.fit()` and `ASR.transform()` functions are just a high level wrapper for `asr_calibrate()` and `asr_process()` adapted to store variables and work with MNE objects.

If you want to go for riemannian ASR, check out Nicolas Barascud's [python_meegkit](https://github.com/nbara/python-meegkit). It's a solid cleaning toolbox with several algorithms, including ASR and rASR. Note that their algorithm is a more conceptually inspired version of (r)ASR, while asrpy aims to be an exact equivalent to the original MATLAB implementation.

Concerning riemannian vs euclidean ASR: I believe that riemannian ASR definitely is theoretically more reasonable. Concerning their performance: I haven't systematically tested their performances against each other, but from experiences that other EEG researchers reported, they don't seem to make much of a difference.

Hope I could help you with that!
Feel free to close this comment if your questions were answered :)

**Comment by DiGyt** [comment]
PS:

I've added an example for how to use asrpy with numpy arrays to the [example notebook](https://github.com/DiGyt/asrpy/blob/main/example.ipynb).

**Comment by sunshineinsandiego** [comment]
Yes, this is super helpful. Thank you!

**Comment by sunshineinsandiego** [comment]
Hi Dirk - Hope you had a great week. Sorry to bother you with another quick question: In an on-line asr processing scenario, my understanding is that eeglab uses a default of non-overlapping 500ms chunks of eeg data. So if I were try to replicate eeglab results using asrpy, I could use the same non-overlapping 500ms windows? (This 500ms non-overlapping window information comes from this paper on rASR https://www.frontiersin.org/articles/10.3389/fnhum.2019.00141/full as I can't seem to find any information on the window size / overlap for eeglab's asr). Any thoughts? Thanks!
